### ISSUE TITLE
Unable to use template-letter and template-contract

### ISSUE THREAD

**Issue by href** [SwissPy/latex-templates#1]
I'm running into various issues trying to compile template-letter and template-contract (template-invoice works fine). I'm not too familiar with LaTeX, so the mistake might be mine. I'm also using MacTeX, though I made sure I use the latest packages.

These are the errors I get, though if I get rid of those (by changing the lco file), I'll hit others and even if it compiles, the result looks horrible (encoding issues, wrong fonts):

```
> rubber -m pdftex --into output/ template-letter.tex
compiling template-letter.tex...
template-letter.tex:19: Package datetime Error: Date `invoicedate' not defined.
template-letter.tex:19: leading text:   \opening{Dear Person,}
```

```
> rubber -m pdftex --into output/ template-contract.tex
compiling template-contract.tex...
template-contract.tex:35: Missing number, treated as zero.
template-contract.tex:35: leading text:     \hspace{\quad}
template-contract.tex:35: Illegal unit of measure (pt inserted).
template-contract.tex:35: leading text:     \hspace{\quad}
```

**Comment by dbrgn** [comment]
Letter template should be fixed now, sorry for the bug.

**Comment by dbrgn** [comment]
Same thing counts for the contract.

**Comment by href** [comment]
All fixed now, thanks :)
