### ISSUE TITLE
Remove VAT line from Invoice

### ISSUE THREAD

**Issue by href** [SwissPy/latex-templates#2]
I think we should remove the VAT line from the invoice. Showing it as 0.00 implies we know that it's zero. Though i would guess that to be true from my understanding of the law I would leave it out because we don't in fact have this cleared by a lawyer.

So by leaving it out we leave are not making a statement in this regard.

**Comment by dbrgn** [comment]
If you change it from `0.0` to `0`, it will disappear (bit of a hack, but that's the way it works).

**Comment by dbrgn** [comment]
Fixed in fdcf864137fdc5ff30ae077f7c8a0a0050fd8bab

**Comment by href** [comment]
Thanks for clarifying.
